version: '3.8'
services:
  openHoursService:
    container_name: OpenHoursApplication
    image: open-hours-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: "java -jar app.jar"

